### ISSUE TITLE
Production bundle without hash

### ISSUE THREAD

**Issue by shevchenkonik** [camjackson/react-app-rewire-micro-frontends#1]
@camjackson hi, do you think it is possible to disable hash generation on production mode?

_Update_
Do you think it makes sense to expand the current package for this? (https://webpack.js.org/configuration/output/#outputfilename)

**Comment by shevchenkonik** [comment]
If you can add an additional flag to define the hash status, I can do PR (https://github.com/shevchenkonik/react-app-rewire-micro-frontends/commit/60e8a72ad9b7a8c35b095db8b0314522fda7f173)

My use case: I have a package and release version is set via CDN, for example (https://cdnjs.com/name-of-library/1.0.1/main.js)

**Comment by camjackson** [comment]
Hi @shevchenkonik, I considered disabling file hashing, but it makes caching (and cache-busting) more difficult, so I decided to go with the approach of fetching the asset-manifest.json at run-time to get the hashed asset filenames.

If you'd prefer to remove the hashes altogether, feel free to fork this project or create your own rewiring from scratch, it's only a few lines of code. Thanks for the suggestion anyway 🙂
